import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Smooth Scrolling",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <nav  className='flex font-[PP] justify-between overflow-hidden'>
      <p id='logo'> Foxel</p>
      <button>Download Now</button>
      </nav>
        {children}
      </body>
    </html>
  );
}
